In [2]:
model_name = "distilgpt2"
device = "cpu"

In [3]:
!pip install transformers torch

Requirement already satisfied: transformers in c:\xampp\htdocs\.venv\lib\site-packages (4.57.1)
Requirement already satisfied: torch in c:\xampp\htdocs\.venv\lib\site-packages (2.9.1)
Requirement already satisfied: filelock in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\xampp\htdocs\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\xampp\htdocs\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\xampp\htdocs\.venv\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\xampp\htdocs\.venv\lib\site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in c:\xampp\htdocs\.venv\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\xampp\htdocs\.venv\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\xampp\htdocs\.venv\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\xampp\htdocs\.venv\lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->transformers) (2025.11.12)

In [4]:
!pip install transformers torch datasets pandas "transformers[torch]"

Requirement already satisfied: transformers in c:\xampp\htdocs\.venv\lib\site-packages (4.57.1)
Requirement already satisfied: torch in c:\xampp\htdocs\.venv\lib\site-packages (2.9.1)
Requirement already satisfied: datasets in c:\xampp\htdocs\.venv\lib\site-packages (4.4.1)
Requirement already satisfied: pandas in c:\xampp\htdocs\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: filelock in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\xampp\htdocs\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\xampp\htdocs\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\xampp\htdocs\.venv\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\xampp\htdocs\.venv\lib\site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in c:\xampp\htdocs\.venv\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: pyarrow>=21.0.0 in c:\xampp\htdocs\.venv\lib\site-packages (from datasets) (22.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in c:\xampp\htdocs\.venv\lib\site-packages (from datasets) (0.4.0)
Requirement already satisfied: httpx<1.0.0 in c:\xampp\htdocs\.venv\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in c:\xampp\htdocs\.venv\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in c:\xampp\htdocs\.venv\lib\site-packages (from datasets) (0.70.18)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\xampp\htdocs\.venv\lib\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: anyio in c:\xampp\htdocs\.venv\lib\site-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: certifi in c:\xampp\htdocs\.venv\lib\site-packages (from httpx<1.0.0->datasets) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\xampp\htdocs\.venv\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\xampp\htdocs\.venv\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\xampp\htdocs\.venv\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\xampp\htdocs\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\xampp\htdocs\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\xampp\htdocs\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: accelerate>=0.26.0 in c:\xampp\htdocs\.venv\lib\site-packages (from transformers[torch]) (1.12.0)
Requirement already satisfied: psutil in c:\xampp\htdocs\.venv\lib\site-packages (from accelerate>=0.26.0->transformers[torch]) (7.1.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\xampp\htdocs\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\xampp\htdocs\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\xampp\htdocs\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\xampp\htdocs\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\xampp\htdocs\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\xampp\htdocs\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\xampp\htdocs\.venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in c:\xampp\htdocs\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\xampp\htdocs\.venv\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\xampp\htdocs\.venv\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\xampp\htdocs\.venv\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\xampp\htdocs\.venv\lib\site-packages (from jinja2->torch) (3.0.3)

In [5]:
from transformers import AutoTokenizer, AutoModelForCausalLM




tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

model= AutoModelForCausalLM.from_pretrained(model_name)

model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-5): 6 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [6]:
 !pip install kagglehub

Requirement already satisfied: kagglehub in c:\xampp\htdocs\.venv\lib\site-packages (0.3.13)
Requirement already satisfied: packaging in c:\xampp\htdocs\.venv\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in c:\xampp\htdocs\.venv\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\xampp\htdocs\.venv\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\xampp\htdocs\.venv\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\xampp\htdocs\.venv\lib\site-packages (from requests->kagglehub) (2025.11.12)
Requirement already satisfied: colorama in c:\xampp\htdocs\.venv\lib\site-packages (from tqdm->kagglehub) (0.4.6)

In [7]:
import pandas as pd 

df = pd.read_csv("wiki_movie_plots_deduped.csv")
df

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...
...,...,...,...,...,...,...,...,...
34881,2014,The Water Diviner,Turkish,Director: Russell Crowe,Director: Russell Crowe\r\nCast: Russell Crowe...,unknown,https://en.wikipedia.org/wiki/The_Water_Diviner,"The film begins in 1919, just after World War ..."
34882,2017,Çalgı Çengi İkimiz,Turkish,Selçuk Aydemir,"Ahmet Kural, Murat Cemcir",comedy,https://en.wikipedia.org/wiki/%C3%87alg%C4%B1_...,"Two musicians, Salih and Gürkan, described the..."
34883,2017,Olanlar Oldu,Turkish,Hakan Algül,"Ata Demirer, Tuvana Türkay, Ülkü Duru",comedy,https://en.wikipedia.org/wiki/Olanlar_Oldu,"Zafer, a sailor living with his mother Döndü i..."
34884,2017,Non-Transferable,Turkish,Brendan Bradley,"YouTubers Shanna Malcolm, Shira Lazar, Sara Fl...",romantic comedy,https://en.wikipedia.org/wiki/Non-Transferable...,The film centres around a young woman named Am...
34885,2017,İstanbul Kırmızısı,Turkish,Ferzan Özpetek,"Halit Ergenç, Tuba Büyüküstün, Mehmet Günsür, ...",romantic,https://en.wikipedia.org/wiki/%C4%B0stanbul_K%...,The writer Orhan Şahin returns to İstanbul aft...

In [8]:
df = df[:1000]
df

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...
...,...,...,...,...,...,...,...,...
995,1930,Playing Around,American,Mervyn LeRoy,"Alice White, Chester Morris",drama,https://en.wikipedia.org/wiki/Playing_Around,Alice White plays the part of a working class ...
996,1930,Raffles,American,George Fitzmaurice,"Ronald Colman, Kay Francis",mystery,https://en.wikipedia.org/wiki/Raffles_(1930_film),Gentleman jewel thief A.J. Raffles (Ronald Col...
997,1930,Reaching for the Moon,American,Edmund Goulding,"Douglas Fairbanks, Edward Everett Horton, Bing...",musical,https://en.wikipedia.org/wiki/Reaching_for_the...,"Wall Street wizard, Larry Day, new to the ways..."
998,1930,Recaptured Love,American,John G. Adolfi,"Belle Bennett, Dorothy Burgess",musical,https://en.wikipedia.org/wiki/Recaptured_Love,"In this drama, a 50-year-old married man (play..."
999,1930,River's End,American,Michael Curtiz,"Charles Bickford, Evalyn Knapp",drama,https://en.wikipedia.org/wiki/River%27s_End_(1...,"In remote northern Canada, Sergeant Conniston ..."

In [9]:
from datasets import Dataset

def map_dataset(batch):
  return tokenizer(
      batch["Plot"],
      truncation=True,
      max_length=128,
      return_overflowing_tokens=True
  )


dataset = Dataset.from_pandas(df)
dataset = dataset.map(
    map_dataset,
    batched=True,
    batch_size=8,
    remove_columns=list(df.columns),
  
)
dataset = dataset.remove_columns(["overflow_to_sample_mapping"])
dataset = dataset.train_test_split(test_size=0.2)
dataset

Map: 100%|██████████| 1000/1000 [00:01<00:00, 931.29 examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 2188
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask'],
        num_rows: 548
    })
})

In [10]:
from transformers import DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

data_collator

DataCollatorForLanguageModeling(tokenizer=GPT2TokenizerFast(name_or_path='distilgpt2', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, clean_up_tokenization_spaces=False, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
}
), mlm=False, whole_word_mask=False, mlm_probability=0.15, mask_replace_prob=0.8, random_replace_prob=0.1, pad_to_multiple_of=None, tf_experimental_compile=False, return_tensors='pt', seed=None)

In [11]:
from transformers import TrainingArguments, Trainer, AutoModelForCausalLM



training_args = TrainingArguments(
    output_dir=".output/model",
    eval_strategy="epoch",
    learning_rate=2e-5,
    weight_decay=0.01,
    num_train_epochs=10,
    per_device_train_batch_size=4,   
    per_device_eval_batch_size=4,
    fp16=False,                      
    dataloader_num_workers=0         
)

trainer = Trainer(
    model=model,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    args=training_args,
    data_collator=data_collator
)


trainer.train()

c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\xampp\htdocs\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

TrainOutput(global_step=5470, training_loss=3.5316600178887683, metrics={'train_runtime': 20958.6425, 'train_samples_per_second': 1.044, 'train_steps_per_second': 0.261, 'total_flos': 712191852380160.0, 'train_loss': 3.5316600178887683, 'epoch': 10.0})

In [12]:
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained("./.output/model/checkpoint-2500")

model

prompt ="A short film about a pilot who"
inputs = tokenizer(prompt, return_tensors="pt").to("cpu")

outputs = model.generate(
    inputs.input_ids,
    max_new_tokens=100,
    do_sample=True,
    top_k=50,
    top_p=0.95
)
outputs

output_string = tokenizer.batch_decode(outputs)

output_string

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

['A short film about a pilot who finds himself trapped in a railroad track has been released to celebrate the 50th anniversary of his death. The final scene, in the film\'s original form (as described in a film magazine in 1958), depicts a strange sequence of flying machines, named "the Flying Circus", which are seen at the entrance to the amusement park. The pilot, who is apparently a pilot for a company, is actually the same pilot who is in a field job as the engineer. However, the machine "hired"']